pokemon:
  - nickname: crawford
    base: cramorant
    generation: 9
    moves:
      - spit-up
      - surf
      - stockpile
      - drill-peck
  - nickname: ramza
    base: dudunsparce
    generation: 9
    moves:
      - calm-mind
      - flamethrower
      - drill-run
      - boomburst
    types:
      - grass
      - null