name: dunspars

on:
  push:
    tags:
      - "v*.*.*"

env:
  CARGO_TERM_COLOR: always

jobs:
  linux_release:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: set_env
      run: |
        RELEASE_TAG=${{github.ref_name}}
        echo "RELEASE_VERSION=${RELEASE_TAG#v}" >> "$GITHUB_ENV"
        echo "RELEASE_CONFIG=.cargo/config-release.toml" >> "$GITHUB_ENV"
    
    - name: create_config
      run: |
        touch $RELEASE_CONFIG
        echo [env] >> $RELEASE_CONFIG
        echo DUNSPARS_VERSION=\"$RELEASE_VERSION\" >> $RELEASE_CONFIG

    - name: build
      run: cargo build --config $RELEASE_CONFIG --release --verbose

    - name: setup
      run: |
        cd target/release
        ./dunspars setup
        cd ../..

    - name: test
      run: cargo test --config $RELEASE_CONFIG --verbose

    - name: archive
      run: tar -czvf dunspars_$RELEASE_VERSION.tar.gz -C target/release dunspars ../../README.md ../../LICENSE

    - name: release
      uses: softprops/action-gh-release@v0.1.15
      with:
        files: dunspars_*.tar.gz
        fail_on_unmatched_files: true