name: Release

on:
  push:
    tags:
      - "v*.*.*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build
      run: cargo build --release --verbose
    - name: GH Release
      uses: softprops/action-gh-release@v0.1.15
      with:
        files: target/release/dunspars
        fail_on_unmatched_files: true